### ISSUE TITLE
typescript build not configured

### ISSUE THREAD

**Issue by ratbeard** [kgroat/create-electron-react-app#5] opened 2018-02-10 15:36 UTC
When I install and run it I get:

```
create-electron-react-app
module.js:529
    throw err;
    ^

Error: Cannot find module './getAnswers'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mfrawley/.nvm/versions/node/v8.6.0/lib/node_modules/create-electron-react-app/src/index.js:3:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Looks like only the root index.ts is getting compiled, not the files inside src.

I was able to work around it by cloning the src, installing ts-node, and running `ts-node index.ts`

**Comment by kgroat** [comment] 2018-12-18 15:43
This is a duplicate of #7; even though this one came first, it seems like there's more discussion over there, so I'm going to keep that one.

**Closed as completed by kgroat** 2018-12-18 15:43 UTC
Labels: bug, duplicate
